### ISSUE TITLE
make settings window height work well in big screen sizes

### ISSUE THREAD

**Issue by synapse25** [knod/read_plugin#64]

**Comment by knod** [comment]
Currently, sizing and scrolling work well for small windows, but with big windows the settings element stays short and requires scrolling, even though there's plenty of room to fit in in the window.

**Comment by knod** [comment]
Fixed with complex resizing in js. Not sure when. Made this demo in the construction of the solution, though: https://jsfiddle.net/fpd4fb80/31/ (this link should appear in the commit at around the same time as the problem was solved).

The function that handles this change in height must be used carefully. If used inappropriately it will prevent the app from appearing at all. More work is needed to make it more robust, but it works and that's enough for now.

*Note: Look into flexbox poly-fills*
